import requests, random, logging, re, os
import datetime

# Setup logging to file
file_handler = logging.FileHandler("log.txt", mode="a")
file_handler.setLevel(logging.INFO)
logging.basicConfig()
logging.root.setLevel(logging.INFO)
file_format = logging.Formatter('%(asctime)s:%(msecs)d %(levelname)s %(message)s')
logger = logging.getLogger("scraper")
logger.addHandler(file_handler)
today = datetime.date.today()

# Load proxies from file
with open("proxies.txt", 'r') as r:
    proxies = r.read().splitlines()

manufacturer_mapping = {
    "Airstream RV": "Airstream RV",
    "Alliance RV": "Alliance RV",
    "American Coach": "American Coach",
    "Black Series Camper": "Black Series Camper",
    "Brinkley": "Brinkley",
    "Coachmen": "Coachmen RV",
    "CrossRoads RV": "CrossRoads RV",
    "Cruiser": "Cruiser",
    "Dave & Matt Vans": "Dave & Matt Vans",
    "DRV Luxury Suites": "DRV Luxury Suites",
    "Dynamax": "Dynamax",
    "EAST TO WEST": "EAST TO WEST",
    "Eclipse": "Eclipse",
    "Ember RV": "Ember RV",
    "Entegra Coach": "Entegra Coach",
    "Fleetwood RV": "Fleetwood RV",
    "Forest River": "Forest River RV",
    "Grand Design": "Grand Design",
    "Grech RV": "Grech RV",
    "Gulf Stream": "Gulf Stream RV",
    "Heartland": "Heartland",
    "Jayco": "Jayco",
    "keystone": "Keystone RV",
    "Lance": "Lance",
    "Midwest Automotive Designs": "Midwest Automotive Designs",
    "Newmar": "Newmar",
    "NeXus RV": "NeXus RV",
    "OGV Luxury": "OGV Luxury",
    "OGV Luxury Coach": "OGV Luxury Coach",
    "Outside Van": "Outside Van",
    "Palomino": "Palomino",
    "Phoenix Cruiser": "Phoenix Cruiser",
    "Pleasure-Way": "Pleasure-Way",
    "Prime Time RV": "Prime Time RV",
    "Regency RV": "Regency RV",
    "Remote Vans": "Remote Vans",
    "Renegade": "Renegade",
    "Roadtrek": "Roadtrek",
    "Storyteller Overland": "Storyteller Overland",
    "Thor": "Thor Motor Coach",
    "Tiffin Motorhomes": "Tiffin Motorhomes",
    "Unknown": "Unknown",
    "Venture RV": "Venture RV",
    "Winnebago": "Winnebago",
    "Winnebago Industries Towables": "Winnebago Industries Towables",
    "Damon": 'Damon',  # Not found in the second list
    "Riverside RV": 'Riverside RV',  # Not found in the second list
    "Highland Ridge": 'Highland Ridge',  # Not found in the second list
    "Dutchmen": 'Dutchmen'  # Not found in the second list
}


# Model mapping
model_map = {
    "allegro open road": "Allegro Open Road",
    "cahaba": "Cahaba",
    "sun lite": "Sun Lite",
    "sun-lite": "Sun-lite",
    "sunray": "Sunray",
    "super lite": "Super Lite",
    "travel star": "Travel Star",
    "flyte": "Flyte",
    "oasis": "Oasis",
    "phoenix": "Phoenix",
    "phoenix lite": "Phoenix Lite",
    "revere": "Revere",
    "shasta": "Shasta",
    "shasta i-5": "Shasta I-5",
    "connect": "Connect",
    "durango": "Durango",
    "sportsmen": "Sportsmen",
    "sportster": "Sportster",
    "vision": "Vision", 
    "barefoot": "Barefoot",
    "cirrus": "Cirrus",
    "t@b": "T@b",
    "t@g": "T@g",
    "bentley": "Bentley",
    "ghost": "Ghost",
    "maybach": "Maybach",
    "phantom": "Phantom",
    "phantom super c": "Phantom Super C",
    "rebel": "Rebel",
    "verrado": "Verrado",
    "viper": "Viper",
    "wraith": "Wraith",
    "cypress": "Cypress",
    "grand star": "Grand Star",
    "kountry star": "Kountry Star",
    "london aire": "London Aire",
    "mountain aire": "Mountain Aire",
    "confluence": "Confluence",
    "connect lite": "Connect Lite",
    "connect mini": "Connect Mini",
    "connect se": "Connect Se",
    "durango 1500": "Durango 1500",
    "durango 2500": "Durango 2500",
    "durango gold": "Durango Gold",
    "durango ht": "Durango Ht",
    "durango sport": "Durango Sport",
    "sportsmen classic": "Sportsmen Classic",
    "sportsmen classic se": "Sportsmen Classic Se",
    "sportsmen le": "Sportsmen Le",
    "sportsmen se": "Sportsmen Se",
    "sportsmen select": "Sportsmen Select",
    "spree connect": "Spree Connect",
    "venom v-series": "Venom V-series",
    "colt": "Colt",
    "cougar hero edition": "Cougar Hero Edition",
    "cougar midnight edition": "Cougar Midnight Edition",
    "impact": "Impact",
    "impact vapor lite": "Impact Vapor Lite",
    "laredo": "Laredo",
    "montanta legacy": "Montanta Legacy",
    "cambria": "Cambria",
    "ellipse": "Ellipse",
    "ellipse ultra": "Ellipse Ultra",
    "meridian": "Meridian",
    "navion": "Navion",
    "reyo": "Reyo",
    "solei": "Solei",
    "suncruiser": "Suncruiser",
    "sunova": "Sunova",
    "sunstar": "Sunstar",
    "sunstar sport": "Sunstar Sport",
    "tribute": "Tribute",
    "flyer": "Flyer",
    "intech rv": "Intech Rv",
    "go play": "Go Play",
    "journeyer": "Journeyer",
    "light": "Light",
    "mesa ridge": "Mesa Ridge",
    "mesa ridge limited": "Mesa Ridge Limited",
    "mesa ridge lite": "Mesa Ridge Lite",
    "mesa ridge s-lite": "Mesa Ridge S-lite",
    "mesa ridge xlt": "Mesa Ridge Xlt",
    "olympia": "Olympia",
    "olympia sport": "Olympia Sport",
    "open range 3x": "Open Range 3x",
    "open range light": "Open Range Light",
    "open range lite": "Open Range Lite",
    "open range lite air": "Open Range Lite Air",
    "open range ultra lite": "Open Range Ultra Lite",
    "roamer": "Roamer",
    "silverstar": "Silverstar",
    "ultra light": "Ultra Light",
    "amer-lite": "Amer-lite",
    "b touring cruiser": "B Touring Cruiser",
    "capri": "Capri",
    "conquest lite": "Conquest Lite",
    "crescendo": "Crescendo",
    "envision": "Envision",
    "gulf breeze": "Gulf Breeze",
    "innsbruck-lite": "Innsbruck-lite",
    "kingsport": "Kingsport",
    "streamlite": "Streamlite",
    "sun voyager": "Sun Voyager",
    "super nova": "Super Nova",
    "svt": "Svt",
    "track & trail": "Track & Trail",
    "trailmaster": "Trailmaster",
    "ultra lite": "Ultra Lite",
    "vintage friendship": "Vintage Friendship",
    "imagine 24": "Imagine 24",
    "serenova": "Serenova",
    "acadia": "Acadia",
    "alpha wolf": "Alpha Wolf",
    "alpha wolf touring": "Alpha Wolf Touring",
    "arctic wolf": "Arctic Wolf",
    "aurora": "Aurora",
    "backpack edition": "Backpack Edition",
    "banshee": "Banshee",
    "berkshire": "Berkshire",
    "berkshire xl": "Berkshire Xl",
    "berkshire xlt": "Berkshire Xlt",
    "blue ridge": "Blue Ridge",
    "campsite ultra": "Campsite Ultra",
    "cardinal": "Cardinal",
    "cardinal estate": "Cardinal Estate",
    "cardinal explorer": "Cardinal Explorer",
    "cardinal limited": "Cardinal Limited",
    "cardinal luxury": "Cardinal Luxury",
    "cardinal red": "Cardinal Red",
    "cascade": "Cascade",
    "cedar creek cottage": "Cedar Creek Cottage",
    "cedar creek experience": "Cedar Creek Experience",
    "cedar creek silverback": "Cedar Creek Silverback",
    "cherokee black label": "Cherokee Black Label",
    "columbus": "Columbus",
    "columbus 1492": "Columbus 1492",
    "columbus castaway": "Columbus Castaway",
    "columbus compass": "Columbus Compass",
    "columbus c-series": "Columbus C-series",
    "evo": "Evo",
    "evo fsx": "Evo Fsx",
    "evo lite": "Evo Lite",
    "evo select": "Evo Select",
    "evo select ce": "Evo Select Ce",
    "flagstaff high wall": "Flagstaff High Wall",
    "flagstaff mac/ltd": "Flagstaff Mac/ltd",
    "flagstaff v-lite": "Flagstaff V-lite",
    "forester ts": "Forester Ts",
    "georgetown": "Georgetown",
    "georgetown 3 series": "Georgetown 3 Series",
    "georgetown xl": "Georgetown Xl",
    "grand surveyor": "Grand Surveyor",
    "grey wolf black label": "Grey Wolf Black Label",
    "ibex": "Ibex",
    "impression": "Impression",
    "independence trail": "Independence Trail",
    "legacy": "Legacy",
    "mustang": "Mustang",
    "nightfall": "Nightfall",
    "nightfall ultra": "Nightfall Ultra",
    "no boundaries rogue river": "No Boundaries Rogue River",
    "palomini": "Palomini",
    "palomino base camp": "Palomino Base Camp",
    "palomino camping trailer": "Palomino Camping Trailer",
    "palomino off road": "Palomino Off Road",
    "patriot": "Patriot",
    "puma le": "Puma Le",
    "puma xle": "Puma Xle",
    "rainier": "Rainier",
    "real lite": "Real Lite",
    "real-lite": "Real-lite",
    "revolve": "Revolve",
    "ridgeview": "Ridgeview",
    "river ranch": "River Ranch",
    "riverstone": "Riverstone",
    "riverstone legacy": "Riverstone Legacy",
    "riverstone reserve": "Riverstone Reserve",
    "rockwood esp": "Rockwood Esp",
    "rockwood freedom": "Rockwood Freedom",
    "rockwood freedom/ltd": "Rockwood Freedom/ltd",
    "rockwood geo pro": "Rockwood Geo Pro",
    "rockwood geo-pro": "Rockwood Geo-pro",
    "rockwood hard site": "Rockwood Hard Site",
    "rockwood high wall": "Rockwood High Wall",
    "rockwood mini lite": "Rockwood Mini Lite",
    "rockwood otg": "Rockwood Otg",
    "rockwood premier": "Rockwood Premier",
    "rockwood signature ultra lite": "Rockwood Signature Ultra Lite",
    "rockwood windjammer": "Rockwood Windjammer",
    "rogue": "Rogue",
    "rogue armored": "Rogue Armored",
    "rogue armored folds of honor edition": "Rogue Armored Folds Of Honor Edition",
    "r-pod": "R-pod",
    "r-pod hood river": "R-pod Hood River",
    "sabre lite": "Sabre Lite",
    "salem cruise lite": "Salem Cruise Lite",
    "salem fsx": "Salem Fsx",
    "salem grand villa": "Salem Grand Villa",
    "salem select": "Salem Select",
    "salem select ce": "Salem Select Ce",
    "salem villa": "Salem Villa",
    "salem villa classic": "Salem Villa Classic",
    "salem villa estate": "Salem Villa Estate",
    "salem villa grand": "Salem Villa Grand",
    "sandpiper c-class": "Sandpiper C-class",
    "sandpiper ht": "Sandpiper Ht",
    "sandpiper luxury": "Sandpiper Luxury",
    "sandstorm": "Sandstorm",
    "sandstorm sport": "Sandstorm Sport",
    "shockwave": "Shockwave",
    "shockwave sport": "Shockwave Sport",
    "sierra": "Sierra",
    "sierra c-class": "Sierra C-class",
    "sierra luxury": "Sierra Luxury",
    "solaire": "Solaire",
    "solaire expandable": "Solaire Expandable",
    "solera": "Solera",
    "sonoma explorer edition": "Sonoma Explorer Edition",
    "sonoma mountain edition": "Sonoma Mountain Edition",
    "stealth": "Stealth",
    "stealth limited": "Stealth Limited",
    "sunseeker le": "Sunseeker Le",
    "sunseeker mbs": "Sunseeker Mbs",
    "sunseeker ts": "Sunseeker Ts",
    "surveyor": "Surveyor",
    "surveyor legend": "Surveyor Legend",
    "surveyor select": "Surveyor Select",
    "surveyor sport": "Surveyor Sport",
    "timberwolf": "Timberwolf",
    "timberwolf black label": "Timberwolf Black Label",
    "tracer": "Tracer",
    "traverse": "Traverse",
    "v-cross": "V-cross",
    "vengeance": "Vengeance",
    "vengeance touring": "Vengeance Touring",
    "vibe": "Vibe",
    "vibe extreme lite": "Vibe Extreme Lite",
    "wildcat": "Wildcat",
    "wildcat maxx": "Wildcat Maxx",
    "wildwood dlx": "Wildwood Dlx",
    "wildwood grand lodge": "Wildwood Grand Lodge",
    "wildwood heritage glen": "Wildwood Heritage Glen",
    "wildwood lodge": "Wildwood Lodge",
    "wildwood select": "Wildwood Select",
    "wildwood select ce": "Wildwood Select Ce",
    "wildwood true north ice lodge": "Wildwood True North Ice Lodge",
    "wolf den": "Wolf Den",
    "wolf den black label": "Wolf Den Black Label",
    "wolf pack": "Wolf Pack",
    "wolf pup": "Wolf Pup",
    "wolf pup black label": "Wolf Pup Black Label",
    "work & play": "Work & Play",
    "xlr boost": "Xlr Boost",
    "xlr hyper lite": "Xlr Hyper Lite",
    "xlr micro boost": "Xlr Micro Boost",
    "xlr nitro": "Xlr Nitro",
    "xlr nitro le": "Xlr Nitro Le",
    "xlr thunderbolt": "Xlr Thunderbolt",
    "angler": "Angler",
    "bounder classic": "Bounder Classic",
    "bounder diesel": "Bounder Diesel",
    "discovery lxe": "Discovery Lxe",
    "evolution": "Evolution",
    "excursion": "Excursion",
    "expedition": "Expedition",
    "flair lxe": "Flair Lxe",
    "highlander": "Highlander",
    "icon": "Icon",
    "jamboree": "Jamboree",
    "jamboree sport": "Jamboree Sport",
    "pace arrow": "Pace Arrow",
    "pace arrow lxe": "Pace Arrow Lxe",
    "prowler": "Prowler",
    "pulse": "Pulse",
    "regal": "Regal",
    "revolution le": "Revolution Le",
    "southwind": "Southwind",
    "storm": "Storm",
    "terra": "Terra",
    "terra lx": "Terra Lx",
    "terry quantum": "Terry Quantum",
    "tioga": "Tioga",
    "wilderness": "Wilderness",
    "accolade": "Accolade",
    "accolade xl": "Accolade Xl",
    "anthem": "Anthem",
    "arc": "Arc",
    "aspire": "Aspire",
    "ethos": "Ethos",
    "ethos li": "Ethos Li",
    "expanse": "Expanse",
    "expanse li": "Expanse Li",
    "odyssey se": "Odyssey Se",
    "qwest se": "Qwest Se",
    "vision xl": "Vision Xl",
    "rog": "Rog",
    "venu": "Venu",
    "e-series": "E-series",
    "overland": "Overland",
    "overland micro": "Overland Micro",
    "touring": "Touring",
    "alta": "Alta",
    "alta le": "Alta Le",
    "alta xtreme 365": "Alta Xtreme 365",
    "blackthorn": "Blackthorn",
    "della terra": "Della Terra",
    "della terra le": "Della Terra Le",
    "entrada": "Entrada",
    "longitude": "Longitude",
    "silver lake": "Silver Lake",
    "silver lake le": "Silver Lake Le",
    "tandara": "Tandara",
    "dynaquest": "Dynaquest",
    "dynaquest touring xl": "Dynaquest Touring Xl",
    "force": "Force",
    "force hd": "Force Hd",
    "isata": "Isata",
    "isata 4": "Isata 4",
    "rev": "Rev",
    "aerolite": "Aerolite",
    "aspen trail": "Aspen Trail",
    "aspen trail le": "Aspen Trail Le",
    "astoria": "Astoria",
    "colorado": "Colorado",
    "denali": "Denali",
    "dutchmen": "Dutchmen",
    "dutchmen lite": "Dutchmen Lite",
    "eddie bauer signature": "Eddie Bauer Signature",
    "endurance": "Endurance",
    "guide compass series": "Guide Compass Series",
    "kodiak cub": "Kodiak Cub",
    "kodiak express": "Kodiak Express",
    "kodiak se": "Kodiak Se",
    "kodiak ultimate": "Kodiak Ultimate",
    "kodiak ultra lite": "Kodiak Ultra Lite",
    "north shore": "North Shore",
    "razorback": "Razorback",
    "rubicon": "Rubicon",
    "rubicon xlt": "Rubicon Xlt",
    "triton": "Triton",
    "voltage": "Voltage",
    "voltage epic series": "Voltage Epic Series",
    "voltage v-series": "Voltage V-series",
    "yukon": "Yukon",
    "elite suites": "Elite Suites",
    "full house": "Full House",
    "essence": "Essence",
    "fun finder": "Fun Finder",
    "hitch": "Hitch",
    "mpg": "Mpg",
    "radiance": "Radiance",
    "shadow cruiser": "Shadow Cruiser",
    "south fork": "South Fork",
    "twilight signature": "Twilight Signature",
    "viewfinder signature": "Viewfinder Signature",
    "altitude": "Altitude",
    "cruiser aire": "Cruiser Aire",
    "elevation": "Elevation",
    "fun time": "Fun Time",
    "hampton": "Hampton",
    "hill country": "Hill Country",
    "longhorn": "Longhorn",
    "longhorn rezerve": "Longhorn Rezerve",
    "redwood": "Redwood",
    "rezerve": "Rezerve",
    "sunset trail reserve": "Sunset Trail Reserve",
    "texan": "Texan",
    "volante": "Volante",
    "z-1": "Z-1",
    "zinger": "Zinger",
    "zinger rezerve": "Zinger Rezerve",
    "americana": "Americana",
    "americana le": "Americana Le",
    "coleman lantern": "Coleman Lantern",
    "coleman lantern lt": "Coleman Lantern Lt",
    "coleman light": "Coleman Light",
    "coleman light lx": "Coleman Light Lx",
    "coleman rubicon": "Coleman Rubicon",
    "grand tour": "Grand Tour",
    "adrenaline": "Adrenaline",
    "apex": "Apex",
    "apex tera": "Apex Tera",
    "beyond": "Beyond",
    "brookstone": "Brookstone",
    "catalina": "Catalina",
    "catalina destination": "Catalina Destination",
    "catalina expedition": "Catalina Expedition",
    "catalina legacy": "Catalina Legacy",
    "catalina sbx": "Catalina Sbx",
    "catalina sport": "Catalina Sport",
    "catalina summit": "Catalina Summit",
    "catalina trailblazer": "Catalina Trailblazer",
    "catalina trail blazer": "Catalina Trail Blazer",
    "clipper": "Clipper",
    "clipper cadet": "Clipper Cadet",
    "clipper classic": "Clipper Classic",
    "clipper express": "Clipper Express",
    "clipper hardside": "Clipper Hardside",
    "clipper ls": "Clipper Ls",
    "clipper sport": "Clipper Sport",
    "concord": "Concord",
    "cross country": "Cross Country",
    "crossfit": "Crossfit",
    "cross trail": "Cross Trail",
    "cross trail transit": "Cross Trail Transit",
    "cross trek": "Cross Trek",
    "encounter": "Encounter",
    "euro": "Euro",
    "freedom express liberty-maple edition": "Freedom Express Liberty-maple Edition",
    "freedom express pilot": "Freedom Express Pilot",
    "freedom express ultra lite": "Freedom Express Ultra Lite",
    "galleria": "Galleria",
    "northern spirit": "Northern Spirit",
    "northern spirit xtr": "Northern Spirit Xtr",
    "nova": "Nova",
    "orion": "Orion",
    "pathfinder": "Pathfinder",
    "prism": "Prism",
    "prism elite": "Prism Elite",
    "prism select": "Prism Select",
    "pursuit precision": "Pursuit Precision",
    "remote": "Remote",
    "spirit ultra lite": "Spirit Ultra Lite",
    "spirit xtr": "Spirit Xtr",
    "sportcoach pathfinder": "Sportcoach Pathfinder",
    "sportscoach cross country": "Sportscoach Cross Country",
    "sportscoach rd": "Sportscoach Rd",
    "viking": "Viking",
    "viking epic": "Viking Epic",
    "viking express": "Viking Express",
    "viking legend": "Viking Legend",
    "viking ls": "Viking Ls",
    "viking ultra-lite": "Viking Ultra-lite",
    "viking v-trec": "Viking V-trec",
    "platinum ii": "Platinum Ii",
    "countryside": "Countryside",
    "dream": "Dream",
    "maverick": "Maverick",
    "rpm": "Rpm",
    "chalet": "Chalet",
    "chalet rv inc": "Chalet Rv Inc",
    "spirit deluxe": "Spirit Deluxe",
    "cameo": "Cameo",
    "carri-lite": "Carri-lite",
    "camp365": "Camp365",
    "braxton creek": "Braxton Creek",
    "bushwacker plus": "Bushwacker Plus",
    "bushwacker teardrop": "Bushwacker Teardrop",
    "bushwhacker": "Bushwhacker",
    "bx": "Bx",
    "free solo": "Free Solo",
    "free solo plus": "Free Solo Plus",
    "black series": "Black Series",
    "black series caravan": "Black Series Caravan",
    "bennche": "Bennche",
    "contessa": "Contessa",
    "patriot thunder": "Patriot Thunder",
    "azur": "Azur",
    "cruiser": "Cruiser",
    "luxe": "Luxe",
    "ice castle 6.5": "Ice Castle 6.5",
    "ice castle 8": "Ice Castle 8",
    "ice castle rv": "Ice Castle Rv",
    "american eagle": "American Eagle",
    "american tradition": "American Tradition",
    "patriot 144sd": "Patriot 144sd",
    "patriot 170ext": "Patriot 170ext",
    "patriot cruiser": "Patriot Cruiser",
    "revolution": "Revolution",
    "tradition": "Tradition",
    'atc' : 'Atc',
    "alpenlite": "Alpenlite",
    "delta": "Delta",
    "delta ultra lite": "Delta Ultra Lite",
    "aliner": "Aliner",
    "ascape": "Ascape",
    "grand ascape": "Grand Ascape",
    "somerset": "Somerset",
    "somerset evolution": "Somerset Evolution",
    "eagle cap": "Eagle Cap",
    "atlas": "Atlas",
    "atlas tommy bahama edition": "Atlas Tommy Bahama Edition",
    "bambi": "Bambi",
    "basecamp": "Basecamp",
    "caravel": "Caravel",
    "classic": "Classic",
    "flying cloud": "Flying Cloud",
    "globetrotter": "Globetrotter",
    "integrity fifth wheel": "Integrity Fifth Wheel",
    "international": "International",
    "international serenity": "International Serenity",
    "international signature": "International Signature",
    "interstate": "Interstate",
    "interstate 19": "Interstate 19",
    "interstate slate": "Interstate Slate",
    "interstate tommy bahama edition": "Interstate Tommy Bahama Edition",
    "nest": "Nest",
    "overlander": "Overlander",
    "pottery barn": "Pottery Barn",
    "rangeline": "Rangeline",
    "safari": "Safari",
    "sport": "Sport",
    "tommy bahama": "Tommy Bahama",
    "tommy bahama relax edition": "Tommy Bahama Relax Edition",
    "trade wind": "Trade Wind",
    'eddie bauer' : 'Eddie Bauer',
    'kodiak' : 'Kodiak',
    'ozark':'Ozark',
    'enlighten' : 'Enlighten',
    'open range' : 'Open Range',
    'retro' : 'Retro',
    'tuscany' : 'Tuscany',
    'campsite reserve' : 'Campsite Reserve',
    'mallard' : 'Mallard',
    'salem' : 'Salem',
    'coleman' : 'Coleman',
    "Valor All-Access" : 'Valor All-Access',
    "access": "Access",
    "ace": "ACE",
    "adventurer": "Adventurer",
    "ahara": "Ahara",
    "airstream tb": "Airstream TB",
    "alante": "Alante",
    "allegro": "Allegro",
    "allegro bay": "Allegro Bay",
    "allegro breeze": "Allegro Breeze",
    "allegro bus": "Allegro Bus",
    "allegro red": "Allegro RED",
    "alpine": "Alpine",
    "ameri-lite": "Ameri-Lite",
    "american patriot": "American Patriot",
    "apex nano": "Apex Nano",
    "apex ultra-lite": "Apex Ultra-Lite",
    "approach": "Approach",
    "arcadia": "Arcadia",
    "arcadia select": "Arcadia Select",
    "arcadia super lite": "Arcadia Super Lite",
    "ascent": "Ascent",
    "atlas": "Atlas",
    "atlas-e atl": "Atlas-e ATL",
    "attitude platinum": "Attitude Platinum",
    "attitude pro series": "Attitude Pro Series",
    "avalanche": "Avalanche",
    "avenger": "Avenger",
    "avenger le": "Avenger LE",
    "avenger lt": "Avenger LT",
    "avenue": "Avenue",
    "avenue all-access": "Avenue All-Access",
    "bambi": "Bambi",
    "basecamp": "Basecamp",
    "bay star": "Bay Star",
    "bay star sport": "Bay Star Sport",
    "big country": "Big Country",
    "bighorn": "Bighorn",
    "black series camper": "Black Series Camper",
    "bounder": "Bounder",
    "bt cruiser": "BT Cruiser",
    "bullet": "Bullet",
    "bullet classic": "Bullet Classic",
    "bullet crossfire": "Bullet Crossfire",
    "byway": "Byway",
    "canyon star": "Canyon Star",
    "caravel": "Caravel",
    "carbon": "Carbon",
    "catalina destination series": "Catalina Destination Series",
    "catalina legacy": "Catalina Legacy",
    "catalina legacy edition": "Catalina Legacy Edition",
    "catalina summit 7": "Catalina Summit 7",
    "catalina summit series 7": "Catalina Summit Series 7",
    "catalina summit series 8": "Catalina Summit Series 8",
    "catalina trail blazer": "Catalina Trail Blazer",
    "cedar creek": "Cedar Creek",
    "challenger": "Challenger",
    "chaparral": "Chaparral",
    "chaparral lite": "Chaparral Lite",
    "chateau": "Chateau",
    "cherokee": "Cherokee",
    "cherokee alpha wolf": "Cherokee Alpha Wolf",
    "cherokee black label": "Cherokee Black Label",
    "cherokee grey wolf": "Cherokee Grey Wolf",
    "cherokee wolf den": "Cherokee Wolf Den",
    "cherokee wolf pack": "Cherokee Wolf Pack",
    "cherokee wolf pup": "Cherokee Wolf Pup",
    "classic": "Classic",
    "comet": "Comet",
    "compass": "Compass",
    "compass awd": "Compass AWD",
    "condor": "Condor",
    "conquest class c": "Conquest Class C",
    "cougar": "Cougar",
    "cougar half-ton": "Cougar Half-Ton",
    "cougar sport": "Cougar Sport",
    "cross trail ev": "Cross Trail EV",
    "cross trail xl": "Cross Trail XL",
    "cyclone": "Cyclone",
    "delano sprinter": "Delano Sprinter",
    "delta": "Delta",
    "delta ultra lite": "Delta Ultra Lite",
    "discovery": "Discovery",
    "dutch star": "Dutch Star",
    "dx3": "DX3",
    "dynaquest xl": "DynaQuest XL",
    "eagle": "Eagle",
    "eagle ht": "Eagle HT",
    "ekko": "Ekko",
    "ekko sprinter": "Ekko Sprinter",
    "emblem": "Emblem",
    "embrace": "Embrace",
    "encore": "Encore",
    "entourage": "Entourage",
    "esteem": "Esteem",
    "europa": "Europa",
    "flagstaff": "Flagstaff",
    "flagstaff classic": "Flagstaff Classic",
    "flagstaff classic super lite": "Flagstaff Classic Super Lite",
    "flagstaff e-pro": "Flagstaff E-Pro",
    "flagstaff hard side": "Flagstaff Hard Side",
    "flagstaff macltd series": "Flagstaff MACLTD Series",
    "flagstaff micro lite": "Flagstaff Micro Lite",
    "flagstaff se": "Flagstaff SE",
    "flagstaff shamrock": "Flagstaff Shamrock",
    "flagstaff super lite": "Flagstaff Super Lite",
    "flair": "Flair",
    "flex": "Flex",
    "flying cloud": "Flying Cloud",
    "flying cloud desk": "Flying Cloud Desk",
    "forester": "Forester",
    "forester le": "Forester LE",
    "forester mbs": "Forester MBS",
    "fortis": "Fortis",
    "forza": "Forza",
    "four winds": "Four Winds",
    "fr3": "FR3",
    "fr3 plus": "FR3 Plus",
    "freedom express": "Freedom Express",
    "freedom express liberty edition": "Freedom Express Liberty Edition",
    "freedom express select": "Freedom Express Select",
    "freelander": "Freelander",
    "friendship": "Friendship",
    "fuzion": "Fuzion",
    "gemini": "Gemini",
    "georgetown 5 series": "Georgetown 5 Series",
    "georgetown 7 series": "Georgetown 7 Series",
    "gh1": "GH1",
    "globetrotter": "Globetrotter",
    "granite ridge": "Granite Ridge",
    "grech": "Grech",
    "greyhawk": "Greyhawk",
    "greyhawk xl": "Greyhawk XL",
    "hideout": "Hideout",
    "hideout sport": "Hideout Sport",
    "hideout sport double axle": "Hideout Sport Double Axle",
    "hideout sport single axle": "Hideout Sport Single Axle",
    "imagine": "Imagine",
    "imagine aim": "Imagine AIM",
    "imagine xls": "Imagine XLS",
    "inception": "Inception",
    "independence trail": "Independence Trail",
    "influence": "Influence",
    "international": "International",
    "interstate": "Interstate",
    "interstate 24gl": "Interstate 24GL",
    "interstate 24x": "Interstate 24X",
    "isata 3": "Isata 3",
    "isata 5": "Isata 5",
    "jay feather": "Jay Feather",
    "jay feather air": "Jay Feather Air",
    "jay feather micro": "Jay Feather Micro",
    "jay flight": "Jay Flight",
    "jay flight bungalow": "Jay Flight Bungalow",
    "jay flight slx": "Jay Flight SLX",
    "lance": "Lance",
    "launch": "Launch",
    "leprechaun": "Leprechaun",
    "lineage": "Lineage",
    "lv series": "LV Series",
    "m-series": "M-Series",
    "magnitude": "Magnitude",
    "melbourne": "Melbourne",
    "melbourne prestige": "Melbourne Prestige",
    "micro minnie": "Micro Minnie",
    "midas": "Midas",
    "milestone": "Milestone",
    "minnie": "Minnie",
    "minnie winnie": "Minnie Winnie",
    "mirada": "Mirada",
    "miramar": "Miramar",
    "mobile suites": "Mobile Suites",
    "model g": "Model G",
    "model z": "Model Z",
    "model z air": "Model Z Air",
    "momentum": "Momentum",
    "momentum g-class": "Momentum G-Class",
    "momentum m-class": "Momentum M-Class",
    "momentum mav": "Momentum MAV",
    "montana": "Montana",
    "montana high country": "Montana High Country",
    "new aire": "New Aire",
    "north point": "North Point",
    "odyssey": "Odyssey",
    "omni": "Omni",
    "ontour": "Ontour",
    "open road allegro": "Open Road Allegro",
    "outlaw": "Outlaw",
    "outlaw class c": "Outlaw Class C",
    "overland series": "Overland Series",
    "palomino": "Palomino",
    "paradigm": "Paradigm",
    "passage 144": "Passage 144",
    "passage 144 awd": "Passage 144 AWD",
    "passage 170ext": "Passage 170EXT",
    "passport": "Passport",
    "passport mini": "Passport Mini",
    "phaeton": "Phaeton",
    "phoenix cruiser": "Phoenix Cruiser",
    "pinnacle": "Pinnacle",
    "plateau": "Plateau",
    "pottery barn special edition": "Pottery Barn Special Edition",
    "precept": "Precept",
    "puma": "Puma",
    "puma destination": "Puma Destination",
    "puma ultra lite": "Puma Ultra Lite",
    "puma unleashed": "Puma Unleashed",
    "puma xle lite": "Puma XLE Lite",
    "pursuit": "Pursuit",
    "quantum": "Quantum",
    "qwest": "Qwest",
    "r pod": "R Pod",
    "rangeline": "Rangeline",
    "reatta xl": "Reatta XL",
    "redhawk": "Redhawk",
    "reflection": "Reflection",
    "reflection 100 series": "Reflection 100 Series",
    "reflection 150 series": "Reflection 150 Series",
    "rei special edition basecamp": "REI Special Edition Basecamp",
    "remote vans": "Remote Vans",
    "residence": "Residence",
    "retreat": "Retreat",
    "revel": "Revel",
    "roadtrek": "Roadtrek",
    "rockwood extreme sports": "Rockwood Extreme Sports",
    "rockwood freedom series": "Rockwood Freedom Series",
    "rockwood geo pro": "Rockwood GEO Pro",
    "rockwood hard side high wall series": "Rockwood Hard Side High Wall Series",
    "rockwood hard side series": "Rockwood Hard Side Series",
    "rockwood high wall series": "Rockwood High Wall Series",
    "rockwood limited series": "Rockwood Limited Series",
    "rockwood mini lite": "Rockwood Mini Lite",
    "rockwood otg": "Rockwood OTG",
    "rockwood roo": "Rockwood Roo",
    "rockwood signature": "Rockwood Signature",
    "rockwood ultra lite": "Rockwood Ultra Lite",
    "sabre": "Sabre",
    "sanctuary": "Sanctuary",
    "sandpiper": "Sandpiper",
    "sandpiper destination trailers": "Sandpiper Destination Trailers",
    "scope": "Scope",
    "seismic": "Seismic",
    "seismic luxury": "Seismic Luxury",
    "seismic luxury series": "Seismic Luxury Series",
    "seneca": "Seneca",
    "sequence": "Sequence",
    "solis": "Solis",
    "solis pocket": "Solis Pocket",
    "solitude": "Solitude",
    "solitude s-class": "Solitude S-Class",
    "solstice": "Solstice",
    "sonic": "Sonic",
    "sonic lite": "Sonic Lite",
    "sportscoach srs": "Sportscoach SRS",
    "sporttrek": "SportTrek",
    "sporttrek touring edition": "SportTrek Touring Edition",
    "springdale": "Springdale",
    "springdale classic": "Springdale Classic",
    "springdale classic mini": "Springdale Classic Mini",
    "springdale mini": "Springdale Mini",
    "storyteller overland": "Storyteller Overland",
    "strada": "Strada",
    "strada-ion": "Strada-ion",
    "strada-ion awd": "Strada-ion AWD",
    "stratus": "Stratus",
    "stratus sport": "Stratus Sport",
    "stryker": "Stryker",
    "sunseeker": "Sunseeker",
    "sunseeker classic": "Sunseeker Classic",
    "sunseeker le": "Sunseeker LE",
    "sunseeker mbs": "Sunseeker MBS",
    "sunset trail": "Sunset Trail",
    "super star": "Super Star",
    "supreme aire": "Supreme Aire",
    "swift": "Swift",
    "swift li": "Swift Li",
    "syncline": "Syncline",
    "tellaro": "Tellaro",
    "terrain": "Terrain",
    "terreno awd": "Terreno AWD",
    "terreno-ion awd": "Terreno-ion AWD",
    "tiburon sprinter": "Tiburon Sprinter",
    "timberwolf": "Timberwolf",
    "touring edition": "Touring Edition",
    "trade wind": "Trade Wind",
    "trail boss": "Trail Boss",
    "transcend": "Transcend",
    "transcend one": "Transcend One",
    "transcend xplor": "Transcend Xplor",
    "travato": "Travato",
    "triumph super c": "Triumph Super C",
    "turismo-ion": "Turismo-ion",
    "turismo-ion awd": "Turismo-ion AWD",
    "ultra brougham": "Ultra Brougham",
    "unknown": "Unknown",
    "v-cruise": "V-Cruise",
    "v-rv": "V-RV",
    "valencia": "Valencia",
    "valor": "Valor",
    "valor all-access": "Valor All-Access",
    "vegas": "Vegas",
    "ventana": "Ventana",
    "veracruz": "Veracruz",
    "verona": "Verona",
    "verona le": "Verona LE",
    "view": "View",
    "vintage cruiser": "Vintage Cruiser",
    "vision": "Vision",
    "vision xl": "Vision XL",
    "vista": "Vista",
    "vista cruiser": "Vista Cruiser",
    "vita": "Vita",
    "voyage": "Voyage",
    "wayfarer": "Wayfarer",
    "white hawk": "White Hawk",
    "wildwood": "Wildwood",
    "wildwood fsx": "Wildwood FSX",
    "wildwood heritage glen": "Wildwood Heritage Glen",
    "wildwood lodge": "Wildwood Lodge",
    "wildwood select": "Wildwood Select",
    "wildwood x-lite": "Wildwood X-Lite",
    "windsport": "Windsport",
    "work and play": "Work and Play",
    "xlr boost": "XLR Boost"
}

# Proxy function
def get_proxy():
    if not proxies:
        return {}

    proxy = random.choice(proxies)
    ip, port, user, password = proxy.split(":")
    proxy = f"http://{user}:{password}@{ip}:{port}"
    proxy = {
        "http": proxy,
        "https": proxy,
    }
    return proxy

# Scraper class
class Scraper:
    def __init__(self, starting_page: int = 1):
        self.starting_page = starting_page
        self.session = requests.session()
        # If no units.csv file create one
        if not os.path.isfile(f"DailyFiles/CampingWorld {today}.csv"):
            self.create_units_csv()

        logger.info("Getting XSRF Token...")
        self.xsrf_token = self.get_xsrf_token()
        self.session.headers.update({
            'accept': '*/*', 'accept-language': 'en-US,en;q=0.9',
            'cache-control': 'no-cache', 'content-type': 'application/json',
            'origin': 'https://rv.campingworld.com', 'pragma': 'no-cache',
            'user-agent': 'Mozilla/5.0 ... Safari/537.36',
            'x-auth-token': self.xsrf_token
        })

    @staticmethod
    def create_units_csv() -> None:
        if not os.path.isfile(f"DailyFiles/CampingWorld {today}.csv"):
            with open(f"DailyFiles/CampingWorld {today}.csv", 'w') as r:
                r.write('Year,Company,Brand,FloorPlan,Msrp,Discount,Stock-Number,Unit Type,Location,Dealer,Date\n')

    def get_xsrf_token(self) -> str:
        headers = {
            'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,...,*/*',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ... Safari/537.36'
        }
        params = {'rv_class': 'tt', 'zip': '23455', 'forcedistance': 'nationwide'}
        response = self.session.get('https://rv.campingworld.com/searchresults', params=params, headers=headers, proxies=get_proxy())
        return "ey" + re.findall('<meta content="ey(.*?)"', response.text)[0]

    def get_page(self, page_num: int) -> dict:
        json_data = {
            'recommended': True,
            'pagination': {'page': page_num, 'take': 12},
            # (other pagination and parameter settings)
        }

        response = self.session.post('https://api.rvs.com/api/v1/asset/search/basic', json=json_data, proxies=get_proxy())
        assets = response.json()['assets']
        if len(assets) == 0:
            return

        return assets

    @staticmethod
    def write_asset_data(asset_data: dict) -> None:
        with open(f"DailyFiles/CampingWorld {today}.csv", 'a') as r:
            r.write(", ".join([str(i) for i in asset_data.values()]))
            r.write("\n")

    # Helper function to find manufacturer
    @staticmethod
    def find_manufacturer(unit_title):
        for manuf_key in manufacturer_mapping:
            if manuf_key.lower() in unit_title.lower():
                return manufacturer_mapping[manuf_key]
        return "Unknown"

    # Helper function to find model
    @staticmethod
    def find_model(unit_title):
        for model_key in model_map:
            if model_key.lower() in unit_title.lower():
                return model_map[model_key]
        return "N/A"

    def get_data_from_asset(self, asset_data) -> dict:
        unit_model = asset_data.get('brand', '')
        unit_company = asset_data.get('make','')
        manufacturer = self.find_manufacturer(unit_company)
        brand = self.find_model(unit_model)
        
        data = {
            "Year": asset_data['year'].strip(),
            "Company": manufacturer.strip(),
            "Brand": brand.strip(),
            "FloorPlan": asset_data['model'].strip(),
            "MSRP": asset_data['totalListPrice'].strip(),
            "Discount Price": asset_data['queryPrice'].strip(),
            "stockNumber": asset_data['stockNumber'].strip(),
            "Category": asset_data['classDisplay'].strip(),
            "Location": f"{asset_data['billingCity']} {asset_data['billingStateCode']}".strip(),
            "Dealer": 'Camping World',
            "Date": today.strip(),
            "condition": asset_data['condition'].strip()
        }
        return data

    def scrape(self) -> None:
        for i in range(self.starting_page, 10000):
            logger.info(f"Getting page {i}...")
            page = self.get_page(i)
            if page is None:
                logger.info("Reached last page, closing...")
                print("Reached last page, closing...")
                return
            else:
                for asset in page:
                    asset_data = self.get_data_from_asset(asset)
                    self.write_asset_data(asset_data)


# Function to run the scraper
def run_scraper(starting_page: int = 1):
    scraper = Scraper(starting_page)
    logger.info("Starting scrape loop...")
    scraper.scrape()


# Entry point for running directly
if __name__ == "__main__":
    run_scraper()
